/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Labyrinth.Adventure;

import game.Main;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        Main classUnderTest = new Main();
    }
}
