package persistence;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Locale;
import java.util.logging.Logger;
import com.jcraft.jsch.*;

import java.util.logging.Level;

public class OracleSqlManager {
    java.sql.Connection connection = null;
    String user;

    private final static Logger LOGGER =
            Logger.getLogger(OracleSqlManager.class.getName());
    public OracleSqlManager(String username, String password) throws SQLException,JSchException{
            super();
            this.connect(username, password);
            this.user = username.toUpperCase(Locale.ROOT);
    }

    /**
     * Runs a query
     * @param query the query to run.
     * @return the Resultset, containing the results of the query, line by line.
     */
    private ResultSet executeQuery(String query)
    {
        ResultSet rs = null;
        try {
            java.sql.Statement stmt = connection.createStatement();
            rs = stmt.executeQuery(query);
        }catch(SQLException e) {
            e.printStackTrace();
        }
        return rs;
    }


    /**
     * Deletes a map from the database.
     * @param mapData the data of the map, which shall be deleted from the database.
     */
    public void deleteMap(String mapData)
    {
        try {
            executeUpdate("DELETE FROM IDU27K.MAPS WHERE mapdata='"+mapData+ "' AND USER='" + this.user +"'");
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * Executes an update command on the SQL server.
     * @param query the update which shall be executed
     * @return the number of lines which were modified
     * @throws SQLException if the syntax is incorrect.
     */
    private int executeUpdate(String query) throws SQLException
    {
        int ret = 0;
            java.sql.Statement stmt = connection.createStatement();
             ret = stmt.executeUpdate(query);
        return ret;
    }

    /**
     * @return a string array, the first element being the alias for the map, and the second is the string representation of the maze.
     */
    public String[] getRandomMap()
    {
        String[] ret = new String[2];
        ResultSet rs = executeQuery("SELECT * FROM(\n" +
                "SELECT * FROM idu27k.maps \n" +
                "ORDER BY DBMS_RANDOM.RANDOM)\n" +
                "WHERE ROWNUM=1");
        try {
        if(!rs.next()) throw new SQLException("No map available!");
                ret[0] = rs.getString(1);
                ret[1] = rs.getString(2);
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return ret;
    }

    /**
     * Saves a map to the database.
     * @param mapData the string representation of the map, generated by the mapbuilder
     * @param alias a nickname for the map, entered by the user.
     * @return zero, if it was executed properly.
     */
    public int saveMap(String mapData,String alias)
    {
        try {
            return executeUpdate("INSERT INTO idu27k.maps\n" +
                    "VALUES('"+mapData+"','" + this.user + "','"+ alias + "')");
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return 0;
    }

    /**
     * Downloads the highscores from the database.
     * @return a string matrix,where each row contains a highscore data containing the name of the user, the score, and the rank.
     */
    public String[][] getHighScores()
    {
        ResultSet rs = executeQuery("SELECT * FROM IDU27K.HIGHSCORES WHERE ROWNUM<=10 ORDER BY SCORE DESC");
            try {
                String[][] highScoreData = new String[10][3];
                int idx=0;
                while(rs.next())
                {
                    highScoreData[idx][0] = ""+ rs.getRow();
                    highScoreData[idx][1] = rs.getString(1);
                    highScoreData[idx++][2] = rs.getString(2);
                }
                return highScoreData;
            } catch (SQLException e) {
                e.printStackTrace();
            }
            return null;
    }

    /**
     * @return all the maps belonging to the user currently logged in.
     */
    public String[][] getMyMaps()
    {
        int size = 0;
        ResultSet rscount = executeQuery("SELECT COUNT(*) FROM IDU27K.MAPS WHERE USERNAME='"+this.user+"'");
        try {
            if(!rscount.next()) return null;
            size = rscount.getInt(1);
        } catch (SQLException e) {
            e.printStackTrace();
        }

        ResultSet rs = executeQuery("SELECT * FROM IDU27K.MAPS WHERE USERNAME='"+this.user+"'");
        String[][] ret = new String[size][3];
            try {
                int idx=0;
                while(rs.next())
                {
                    ret[idx][0] = rs.getString(1);
                    ret[idx][1] = rs.getString(2);
                    ret[idx++][2] = rs.getString(3);
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
            return ret;
    }

    public int getHighScore()
    {
        ResultSet rs = executeQuery("SELECT score from IDU27K.HIGHSCORES WHERE USERNAME='" + this.user + "'");
        try {
            if(rs.next())
            {
                System.out.println(rs.getInt(1));
            return rs.getInt(1);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return 0;
    }

    public int saveHighScore(int value)
    {
        try{
            return executeUpdate("INSERT INTO IDU27K.HIGHSCORES VALUES('"+ this.user + "',"+ value + ")");
            } catch (SQLException ex) {
            try {
                return executeUpdate("UPDATE (SELECT SCORE FROM HIGHSCORES WHERE USERNAME='"+this.user +"') SET SCORE="+value);
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
        return 0;
    }

    public void connect(String username, String pw) throws SQLException, JSchException{
        int assigned_port = 0;
        final int local_port=2345;
        final int remote_port=1521;
        final String remote_host="caesar.elte.hu";
            JSch jsch = new JSch();
            Session session = jsch.getSession("lkcsdvd", remote_host, 22);
            session.setPassword("szakdolgozatmiattipublikusjelszo1");
            java.util.Properties config = new java.util.Properties();
            config.put("StrictHostKeyChecking", "no");
            config.put("Compression", "yes");
            config.put("ConnectionAttempts","2");
            session.setConfig(config);
            session.connect();
            try{
                assigned_port = session.setPortForwardingL(local_port,
                        "aramis.inf.elte.hu", remote_port);
            }catch(JSchException e)
            {}

        if (assigned_port == 0) {
            LOGGER.log(Level.SEVERE, "Port forwarding failed !");
        }
        final String database_user=username;
        final String database_password=pw;
        String url = "jdbc:oracle:thin:"+ database_user+ "/" + database_password + "@//localhost:2345/aramis";
        connection = java.sql.DriverManager.getConnection(url);
        }
}


